export type CatalogField = { key: string; label: string; ar: string }
export type CatalogScreen = { id: string; name: string; app: 'الكابتن' | 'المحل'; group: string; fields: CatalogField[] }
export type CatalogCopy = { key: string; ar: string; place: string }
export type CatalogTpl = { event: string; to: string; channel: string; title: string; body: string }
export type CatalogOption = { id: string; group: string; app: string; label: string }

export const CAPTAIN_SCREENS: CatalogScreen[] = [
  { id: 'c-welcome', name: 'شاشة الترحيب', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'captain_welcome_title', label: 'العنوان', ar: 'أهلاً بك في كابتن زاجل ديلفري!' },
    { key: 'captain_welcome_subtitle', label: 'النص', ar: 'يوصلك بسرعة وثقة - انضم لفريق كباتن زاجل في العراق وأنشئ مدخولك اليومي.' },
    { key: 'btn_captain_register', label: 'زر التسجيل', ar: 'تسجيل حساب كابتن جديد' },
    { key: 'btn_captain_login', label: 'زر الدخول', ar: 'تسجيل الدخول لحسابك' },
  ]},
  { id: 'c-signup-1', name: 'التسجيل — البيانات الشخصية', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'signup_title', label: 'عنوان الشاشة', ar: 'إنشاء حساب كابتن' },
    { key: 'step_1_personal', label: 'الخطوة 1', ar: '1. البيانات الشخصية' },
    { key: 'step_2_docs', label: 'الخطوة 2', ar: '2. رفع الوثائق العراقية' },
    { key: 'step_3_review', label: 'الخطوة 3', ar: '3. المراجعة والإرسال' },
    { key: 'field_fullname', label: 'حقل الاسم', ar: 'الاسم الثلاثي (كما في الهوية)' },
    { key: 'field_phone', label: 'حقل الهاتف', ar: 'رقم الهاتف' },
    { key: 'field_gmail', label: 'حقل البريد', ar: 'حساب البريد الإلكتروني (Gmail)' },
    { key: 'field_password', label: 'حقل كلمة المرور', ar: 'كلمة المرور' },
    { key: 'field_password_confirm', label: 'تأكيد كلمة المرور', ar: 'تأكيد كلمة المرور' },
    { key: 'field_vehicle_type', label: 'نوع المركبة', ar: 'نوع وسيلة النقل' },
    { key: 'field_governorate_select', label: 'المحافظة', ar: 'المحافظة التي تعمل بها' },
    { key: 'btn_next', label: 'زر التالي', ar: 'التالي ←' },
    { key: 'err_required', label: 'خطأ حقل فارغ', ar: 'هذا الحقل مطلوب' },
    { key: 'err_gmail', label: 'خطأ البريد', ar: 'أدخل بريد Gmail صحيح' },
    { key: 'err_password_mismatch', label: 'خطأ التطابق', ar: 'كلمة المرور غير متطابقة' },
  ]},
  { id: 'c-signup-2', name: 'التسجيل — الوثائق', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'docs_title', label: 'العنوان', ar: 'رفع الوثائق المطلوبة' },
    { key: 'doc_national_card_front', label: 'وجه الهوية', ar: 'صورة وجه البطاقة الموحدة / الهوية الوطنية' },
    { key: 'doc_national_card_back', label: 'ظهر الهوية', ar: 'صورة ظهر البطاقة الموحدة / الهوية الوطنية' },
    { key: 'doc_residence_card_front', label: 'وجه بطاقة السكن', ar: 'صورة وجه بطاقة السكن' },
    { key: 'doc_residence_card_back', label: 'ظهر بطاقة السكن', ar: 'صورة ظهر بطاقة السكن' },
    { key: 'btn_take_photo', label: 'الكاميرا', ar: 'التقاط صورة بالكاميرا 📷' },
    { key: 'btn_pick_gallery', label: 'المعرض', ar: 'اختيار من معرض الصور 🖼️' },
    { key: 'doc_not_uploaded', label: 'حالة فارغة', ar: 'لم يتم الرفع' },
    { key: 'err_docs_missing', label: 'خطأ النقص', ar: 'يرجى رفع جميع الوثائق المطلوبة' },
    { key: 'btn_prev', label: 'السابق', ar: '→ السابق' },
  ]},
  { id: 'c-signup-3', name: 'التسجيل — المراجعة', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'review_title', label: 'العنوان', ar: 'مراجعة البيانات' },
    { key: 'btn_submit_registration', label: 'زر الإرسال', ar: 'إرسال الطلب ✅' },
    { key: 'msg_sending', label: 'التحميل', ar: 'جاري إرسال طلبك...' },
    { key: 'err_submit_failed', label: 'فشل الإرسال', ar: 'حدث خطأ أثناء الإرسال. حاول مرة أخرى' },
    { key: 'btn_retry', label: 'إعادة المحاولة', ar: 'إعادة المحاولة' },
  ]},
  { id: 'c-pending', name: 'انتظار الموافقة', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'msg_registration_submitted', label: 'نجاح الإرسال', ar: 'تم إرسال طلب انضمامك لـ زاجل ديلفري بنجاح!' },
    { key: 'msg_under_review_title', label: 'العنوان', ar: 'طلبك قيد المراجعة ⏳' },
    { key: 'msg_under_review_desc', label: 'النص', ar: 'فريق زاجل ديلفري يراجع وثائقك حالياً. سيصلك إشعار فور تفعيل الحساب.' },
    { key: 'status_pending', label: 'الحالة', ar: 'بانتظار الموافقة' },
  ]},
  { id: 'c-rejected', name: 'شاشة الرفض', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'reject_title', label: 'العنوان', ar: 'تم رفض طلب التسجيل' },
    { key: 'reject_reason_prefix', label: 'بادئة السبب', ar: 'سبب الرفض:' },
    { key: 'btn_reapply', label: 'إعادة التقديم', ar: 'تقديم طلب جديد' },
    { key: 'btn_contact_support', label: 'الدعم', ar: 'تواصل مع الدعم' },
    { key: 'reapply_banner', label: 'تنبيه إعادة التقديم', ar: 'تم رفض طلبك السابق. يمكنك تعديل البيانات وإعادة التقديم.' },
  ]},
  { id: 'c-login', name: 'تسجيل الدخول', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'login_phone', label: 'الهاتف', ar: 'رقم الهاتف' },
    { key: 'login_password', label: 'كلمة المرور', ar: 'كلمة المرور' },
    { key: 'btn_login', label: 'الزر', ar: 'تسجيل الدخول' },
    { key: 'forgot_password_link', label: 'نسيت', ar: 'نسيت كلمة المرور؟' },
  ]},
  { id: 'c-forgot', name: 'استعادة كلمة المرور', app: 'الكابتن', group: 'الدخول والتسجيل', fields: [
    { key: 'forgot_title', label: 'العنوان', ar: 'استعادة كلمة المرور' },
    { key: 'forgot_desc', label: 'النص', ar: 'أدخل رقم هاتفك المسجل وسنرسل لك رمز التحقق.' },
    { key: 'btn_send_otp', label: 'إرسال الرمز', ar: 'إرسال رمز التحقق' },
    { key: 'otp_title', label: 'عنوان الرمز', ar: 'أدخل رمز التحقق' },
    { key: 'otp_sent', label: 'تم الإرسال', ar: 'تم إرسال رمز مكون من 4 أرقام إلى الرقم' },
    { key: 'otp_resend_after', label: 'العدّاد', ar: 'إعادة إرسال الرمز بعد' },
    { key: 'otp_resend', label: 'إعادة الإرسال', ar: 'إعادة إرسال الرمز' },
    { key: 'otp_change_phone', label: 'تغيير الرقم', ar: 'تغيير رقم الهاتف' },
    { key: 'err_otp_wrong', label: 'رمز خاطئ', ar: 'الرمز غير صحيح. حاول مرة أخرى.' },
    { key: 'err_otp_limit', label: 'تجاوز المحاولات', ar: 'تم تجاوز عدد المحاولات. أعد إرسال الرمز.' },
    { key: 'new_pass_title', label: 'عنوان الجديدة', ar: 'كلمة المرور الجديدة' },
    { key: 'btn_change_password', label: 'زر التغيير', ar: 'تغيير كلمة المرور' },
    { key: 'pass_changed_title', label: 'نجاح', ar: 'تم تغيير كلمة المرور بنجاح' },
    { key: 'pass_changed_desc', label: 'نص النجاح', ar: 'يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.' },
  ]},
  { id: 'c-suspended', name: 'كابتن موقوف', app: 'الكابتن', group: 'حالات الحساب', fields: [
    { key: 'captain_suspended_title', label: 'العنوان', ar: 'حسابك موقوف' },
    { key: 'captain_suspended_body', label: 'النص', ar: 'تم إيقاف حسابك من قبل إدارة زاجل ديلفري. السبب الموضح: {reason}. يرجى التواصل مع الإدارة لمراجعة التفعيل.' },
    { key: 'suspended_contact', label: 'زر التواصل', ar: '📞 تواصل مع الإدارة' },
    { key: 'link_logout', label: 'تسجيل الخروج', ar: 'تسجيل الخروج' },
  ]},
  { id: 'c-session', name: 'انتهاء الجلسة', app: 'الكابتن', group: 'حالات الحساب', fields: [
    { key: 'session_title', label: 'العنوان', ar: 'انتهت جلستك' },
    { key: 'session_desc', label: 'النص', ar: 'لأسباب أمنية، تم تسجيل خروجك. يرجى تسجيل الدخول مرة أخرى.' },
    { key: 'session_other_account', label: 'حساب آخر', ar: 'تسجيل الدخول بحساب آخر' },
    { key: 'session_restored', label: 'استعادة', ar: 'تم استعادة بياناتك. أكمل من حيث توقفت.' },
  ]},
  { id: 'c-force-update', name: 'التحديث الإجباري / الاختياري', app: 'الكابتن', group: 'حالات الحساب', fields: [
    { key: 'update_required_title', label: 'عنوان إجباري', ar: 'تحديث مطلوب' },
    { key: 'update_required_desc', label: 'نص إجباري', ar: 'إصدار تطبيقك الحالي قديم ولا يدعم الاستمرار. يرجى التحديث للمتابعة.' },
    { key: 'btn_update_now', label: 'تحديث الآن', ar: 'تحديث الآن' },
    { key: 'update_optional_title', label: 'عنوان اختياري', ar: 'تحديث جديد متاح' },
    { key: 'update_optional_desc', label: 'نص اختياري', ar: 'يتوفر إصدار جديد من التطبيق مع تحسينات وإصلاحات.' },
    { key: 'btn_later', label: 'لاحقاً', ar: 'لاحقاً' },
  ]},
  { id: 'c-maintenance', name: 'وضع الصيانة', app: 'الكابتن', group: 'حالات الحساب', fields: [
    { key: 'maintenance_title', label: 'العنوان', ar: 'النظام في وضع الصيانة' },
    { key: 'maintenance_desc', label: 'النص', ar: 'نعتذر عن الإزعاج. النظام في وضع صيانة مؤقت. سنعود قريباً.' },
    { key: 'btn_try_later', label: 'لاحقاً', ar: 'محاولة لاحقاً' },
  ]},
  { id: 'c-shift', name: 'اختيار الشفت', app: 'الكابتن', group: 'التشغيل', fields: [
    { key: 'title_shift_selection', label: 'العنوان', ar: 'اختر شفت العمل الأسبوعي' },
    { key: 'desc_shift_selection', label: 'النص', ar: 'يمكنك تغيير شفت عملك مرة واحدة فقط خلال الأسبوع.' },
    { key: 'btn_confirm_shift', label: 'التأكيد', ar: 'تأكيد اختيار الشفت' },
    { key: 'shift_change_limit', label: 'نفاد الفرصة', ar: 'لقد استخدمت فرصة تغيير الشفت هذا الأسبوع. يمكنك التغيير الأسبوع القادم.' },
    { key: 'shift_confirm_q', label: 'سؤال التأكيد', ar: 'هل تريد اختيار هذا الشفت؟ لن تتمكن من تغييره إلا مرة واحدة هذا الأسبوع.' },
  ]},
  { id: 'c-home', name: 'الشاشة الرئيسية', app: 'الكابتن', group: 'التشغيل', fields: [
    { key: 'toggle_duty_on', label: 'متصل', ar: 'أنت متصل الآن (تستقبل طلبيات زاجل) 🟢' },
    { key: 'toggle_duty_off', label: 'غير متصل', ar: 'أنت غير متصل (توقف استقبال الطلبيات) 🔴' },
    { key: 'err_outside_shift', label: 'خارج الشفت', ar: 'عذراً يا كابتن! أنت خارج وقت شفتك المعتمد ({shift_time}). لا يمكنك الاتصال واستقبال الطلبيات الآن.' },
    { key: 'btn_checkin_attendance', label: 'الحضور', ar: 'تسجيل الحضور للشفت ✅' },
    { key: 'home_active_orders', label: 'الطلبات النشطة', ar: 'طلباتك النشطة' },
    { key: 'home_no_active', label: 'فارغ نشط', ar: 'لا توجد طلبات نشطة حالياً' },
    { key: 'home_recent', label: 'آخر الطلبات', ar: 'آخر الطلبات' },
    { key: 'nav_home', label: 'تبويب الرئيسية', ar: 'الرئيسية' },
    { key: 'nav_history', label: 'تبويب السجل', ar: 'سجل الطلبات' },
    { key: 'nav_ledger', label: 'تبويب الكشف', ar: 'كشف الحساب' },
    { key: 'nav_profile', label: 'تبويب الملف', ar: 'الملف الشخصي' },
    { key: 'disconnect_confirm', label: 'تأكيد قطع الاتصال', ar: 'هل تريد قطع الاتصال؟ لن تستلم طلبات جديدة.' },
  ]},
  { id: 'c-attendance', name: 'تسجيل الحضور', app: 'الكابتن', group: 'التشغيل', fields: [
    { key: 'checkin_ok', label: 'نجاح الحضور', ar: 'تم تسجيل حضورك بنجاح. شفت سعيد! 🎉' },
    { key: 'checkin_outside', label: 'خارج الشفت', ar: 'لا يمكنك تسجيل الحضور خارج وقت شفتك.' },
    { key: 'checkin_offline', label: 'غير متصل', ar: 'يرجى الاتصال أولاً لتسجيل الحضور.' },
    { key: 'end_shift_q', label: 'إنهاء الشفت', ar: 'هل تريد إنهاء شفتك؟' },
  ]},
  { id: 'c-new-order', name: 'تنبيه الطلب الجديد', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'alert_new_order_title', label: 'العنوان', ar: '🚚 طلبية جديدة من زاجل ديلفري!' },
    { key: 'lbl_order_timer', label: 'المهلة', ar: 'المهلة المتبقية للقبول:' },
    { key: 'lbl_shop_name', label: 'المحل', ar: 'المحل/المطعم:' },
    { key: 'lbl_pickup_district', label: 'الاستلام', ar: 'منطقة الاستلام:' },
    { key: 'lbl_dropoff_district', label: 'التوصيل', ar: 'منطقة التوصيل:' },
    { key: 'lbl_item_price', label: 'قيمة الطلب', ar: 'مبلغ الطلبية للمحل:' },
    { key: 'lbl_delivery_fee', label: 'الأجرة', ar: 'أجرة التوصيل لك:' },
    { key: 'btn_accept_order', label: 'قبول', ar: 'قبول الطلبية ✅' },
    { key: 'btn_reject_order', label: 'رفض', ar: 'رفض الطلبية ❌' },
    { key: 'reject_confirm', label: 'تأكيد الرفض', ar: 'هل تريد رفض هذا الطلب؟' },
    { key: 'timeout_toast', label: 'انتهاء المهلة', ar: 'انتهت مهلة الاستجابة. تم إرسال الطلب لكابتن آخر.' },
    { key: 'taken_by_other', label: 'سبق القبول', ar: 'عذراً، تم قبول هذا الطلب من قبل كابتن آخر.' },
  ]},
  { id: 'c-to-shop', name: 'متوجه للمحل', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'step_to_shop', label: 'المرحلة', ar: 'متوجه إلى المحل/المطعم' },
    { key: 'btn_action_arrived_shop', label: 'الزر', ar: '📍 وصلت للمحل' },
    { key: 'btn_emergency', label: 'طوارئ', ar: '⚠️ طوارئ' },
    { key: 'arrived_shop_q', label: 'تأكيد الوصول', ar: 'هل وصلت لموقع المحل؟' },
  ]},
  { id: 'c-at-shop', name: 'وصل المحل / الاستلام', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'step_at_shop', label: 'المرحلة', ar: 'وصلت لموقع المحل' },
    { key: 'at_shop_hint', label: 'التعليمات', ar: 'ادخل المحل واستلم الطلب.' },
    { key: 'btn_action_item_received', label: 'الاستلام', ar: '✅ استلمت الطلبية ودفعت {amount} د.ع للمحل' },
    { key: 'btn_photo_pickup', label: 'تصوير', ar: '📷 تصوير الطلب عند الاستلام' },
    { key: 'pickup_confirm', label: 'تأكيد الاستلام', ar: 'هل استلمت الطلب ودفعت القيمة للمحل؟' },
  ]},
  { id: 'c-to-customer', name: 'بالطريق للزبون', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'step_to_customer', label: 'المرحلة', ar: 'بالطريق إلى الزبون' },
    { key: 'lbl_customer_pay', label: 'المبلغ', ar: 'المبلغ المطلوب من الزبون:' },
    { key: 'btn_action_arrived_customer', label: 'الوصول', ar: '📍 وصلت للزبون' },
    { key: 'btn_action_complete_delivery', label: 'التسليم', ar: '✅ تم تسليم الطلبية وتحصيل {total} د.ع من الزبون' },
  ]},
  { id: 'c-pod', name: 'إثبات التسليم', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'pod_title', label: 'العنوان', ar: 'إثبات التسليم للزبون' },
    { key: 'pod_desc', label: 'النص', ar: 'أكمل إثبات التسليم لإتمام الطلب.' },
    { key: 'pod_otp_desc', label: 'OTP', ar: 'أدخل رمز التحقق (OTP) المتكون من 4 أرقام المرسل لرقم الزبون عبر SMS:' },
    { key: 'btn_send_sms_otp', label: 'إرسال SMS', ar: '📩 إرسال رمز OTP للزبون' },
    { key: 'pod_photo_fallback', label: 'بديل الصورة', ar: 'لم يصل الرمز للزبون؟ التقط صورة إثبات التسليم بدلاً من ذلك 📷' },
    { key: 'btn_finish_pod', label: 'إتمام', ar: 'إتمام التسليم' },
    { key: 'err_otp_pod', label: 'OTP خاطئ', ar: 'رمز OTP غير صحيح. حاول مرة أخرى.' },
    { key: 'err_otp_pod_limit', label: 'تجاوز OTP', ar: 'تم تجاوز عدد المحاولات. يمكنك إتمام التسليم بالصورة أو التواصل مع الإدارة.' },
  ]},
  { id: 'c-success', name: 'نجاح التسليم', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'success_title', label: 'العنوان', ar: 'تم التسليم بنجاح! 🎉' },
    { key: 'btn_back_home', label: 'الرئيسية', ar: 'العودة للرئيسية' },
    { key: 'btn_view_order', label: 'التفاصيل', ar: 'عرض تفاصيل الطلب' },
    { key: 'btn_rate_shop', label: 'تقييم المحل', ar: 'تقييم المحل' },
  ]},
  { id: 'c-cancel', name: 'إلغاء الطلب', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'cancel_title', label: 'العنوان', ar: 'إلغاء الطلب' },
    { key: 'cancel_warn', label: 'تحذير', ar: '⚠️ إلغاء الطلبات المتكرر قد يؤثر على تقييمك.' },
    { key: 'btn_confirm_cancel', label: 'تأكيد', ar: 'تأكيد الإلغاء' },
  ]},
  { id: 'c-issue', name: 'مشكلة في التسليم / المرتجع', app: 'الكابتن', group: 'تنفيذ الطلب', fields: [
    { key: 'issue_delivery_problem', label: 'العنوان', ar: '⚠️ مشكلة في التسليم' },
    { key: 'issue_pick', label: 'النص', ar: 'اختر المشكلة التي تواجهها مع هذا الطلب.' },
    { key: 'issue_opt_no_answer', label: 'لا يرد', ar: '📞 الزبون لا يرد على الاتصال' },
    { key: 'issue_opt_not_home', label: 'غير موجود', ar: '🏠 الزبون غير موجود في العنوان' },
    { key: 'issue_opt_refused', label: 'رفض الاستلام', ar: '❌ الزبون يرفض استلام الطلبية' },
    { key: 'issue_opt_refused_pay', label: 'رفض الدفع', ar: '💰 الزبون يرفض دفع المبلغ' },
    { key: 'issue_opt_bad_address', label: 'عنوان خاطئ', ar: '📍 العنوان خاطئ أو غير دقيق' },
    { key: 'issue_opt_cant_access', label: 'لا وصول', ar: '🚪 لا أستطيع الوصول للموقع' },
    { key: 'issue_opt_other', label: 'أخرى', ar: '❓ مشكلة أخرى' },
    { key: 'btn_log_issue', label: 'تسجيل', ar: 'تسجيل المشكلة' },
    { key: 'issue_wait', label: 'انتظار', ar: 'الانتظار 10 دقائق ثم المحاولة مرة أخرى' },
    { key: 'btn_return_to_shop', label: 'إرجاع', ar: '🔄 إرجاع الطلبية للمحل واسترداد المبلغ' },
    { key: 'btn_refund_confirmed', label: 'استرداد', ar: '✅ أعدت الطلبية للمحل واسترددت الكاش' },
    { key: 'refund_q', label: 'سؤال الاسترداد', ar: 'أعدت الطلبية للمحل. هل استلمت المبلغ كاملاً من صاحب المحل؟' },
    { key: 'refund_no', label: 'لم يستلم', ar: '❌ لا، لم أستلم بعد / المحل يرفض الاسترجاع' },
  ]},
  { id: 'c-offline', name: 'وضع عدم الاتصال', app: 'الكابتن', group: 'التشغيل', fields: [
    { key: 'offline_bar', label: 'الشريط', ar: '⚠️ وضع عدم الاتصال. يمكنك إكمال التوصيل الحالي فقط.' },
    { key: 'online_bar', label: 'عودة الاتصال', ar: '✅ عاد الاتصال. جاري مزامنة البيانات...' },
    { key: 'sync_ok', label: 'نجاح المزامنة', ar: 'تمت المزامنة بنجاح.' },
  ]},
  { id: 'c-ledger', name: 'كشف الحساب', app: 'الكابتن', group: 'المحاسبة', fields: [
    { key: 'title_captain_ledger', label: 'العنوان', ar: 'كشف الحساب اليومي' },
    { key: 'ledger_notice', label: 'تنبيه', ar: 'تنبيه: هذا تقرير محاسبي نقدية (كاش) لضبط الحسابات وليس محفظة إلكترونية.' },
    { key: 'lbl_total_paid_shops', label: 'دفع للمحلات', ar: 'مجموع ما دفعته للمحلات:' },
    { key: 'lbl_total_collected_customers', label: 'استلام من الزبائن', ar: 'مجموع ما استلمته من الزبائن:' },
    { key: 'lbl_net_delivery_earnings', label: 'صافي الأجرة', ar: 'صافي أجور التوصيل (أرباحك):' },
    { key: 'lbl_settlement_status', label: 'التسوية', ar: 'حالة التسوية المالية مع الإدارة:' },
    { key: 'btn_export_ledger', label: 'تصدير', ar: '📥 تصدير الكشف' },
    { key: 'tab_canceled_orders', label: 'تبويب الملغاة', ar: 'الطلبات الملغاة' },
  ]},
  { id: 'c-history', name: 'سجل الطلبات', app: 'الكابتن', group: 'المحاسبة', fields: [
    { key: 'history_title', label: 'العنوان', ar: 'سجل الطلبات' },
    { key: 'history_search', label: 'بحث', ar: 'ابحث برقم الطلب أو اسم المحل' },
    { key: 'history_empty', label: 'فارغ', ar: 'لا توجد طلبات مطابقة.' },
  ]},
  { id: 'c-stats', name: 'إحصائياتي', app: 'الكابتن', group: 'المحاسبة', fields: [
    { key: 'stats_title', label: 'العنوان', ar: 'إحصائياتي' },
  ]},
  { id: 'c-rate-shop', name: 'تقييم المحل', app: 'الكابتن', group: 'المحاسبة', fields: [
    { key: 'rate_shop_title', label: 'العنوان', ar: 'تقييم المحل' },
    { key: 'rate_shop_q', label: 'السؤال', ar: 'كيف كانت تجربتك مع هذا المحل؟' },
    { key: 'rate_ready_q', label: 'الجاهزية', ar: 'هل كان الطلب جاهزاً عند وصولك؟' },
    { key: 'rate_deal_q', label: 'التعامل', ar: 'هل كان التعامل جيداً؟' },
    { key: 'btn_send_rate', label: 'إرسال', ar: 'إرسال التقييم' },
    { key: 'btn_skip', label: 'تخطي', ar: 'تخطي' },
    { key: 'rate_thanks', label: 'شكراً', ar: 'شكراً لتقييمك! ⭐' },
  ]},
  { id: 'c-sos', name: 'الطوارئ', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'sos_title', label: 'العنوان', ar: '🚨 طوارئ' },
    { key: 'sos_desc', label: 'النص', ar: 'اضغط الزر أدناه لإرسال تنبيه طوارئ للإدارة مع تفاصيل موقعك وطلبك.' },
    { key: 'btn_sos', label: 'الزر', ar: '🚨 إرسال تنبيه طوارئ' },
    { key: 'sos_confirm', label: 'تأكيد', ar: 'هل تريد إرسال تنبيه طوارئ للإدارة؟' },
    { key: 'sos_sent', label: 'تم', ar: 'تم إرسال تنبيه الطوارئ. ستتواصل معك الإدارة قريباً.' },
  ]},
  { id: 'c-profile', name: 'الملف الشخصي', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'profile_title', label: 'العنوان', ar: 'الملف الشخصي' },
    { key: 'opt_change_shift', label: 'تغيير الشفت', ar: 'تغيير الشفت' },
    { key: 'opt_change_password', label: 'كلمة المرور', ar: 'تغيير كلمة المرور' },
    { key: 'opt_update_docs', label: 'الوثائق', ar: 'تحديث الوثائق' },
    { key: 'opt_logout', label: 'خروج', ar: 'تسجيل الخروج' },
  ]},
  { id: 'c-docs-update', name: 'تحديث الوثائق', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'docs_update_title', label: 'العنوان', ar: 'تحديث الوثائق' },
    { key: 'docs_update_desc', label: 'النص', ar: 'يرجى تحديث الوثائق التالية للمتابعة في استلام الطلبات.' },
    { key: 'btn_send_review', label: 'إرسال', ar: 'إرسال للمراجعة' },
    { key: 'docs_banner', label: 'شريط الرئيسية', ar: '⚠️ وثائقك ناقصة أو منتهية. حدّثها الآن.' },
    { key: 'docs_block_orders', label: 'منع الطلبات', ar: '⚠️ تم إيقاف استلام الطلبات مؤقتاً بسبب نقص الوثائق. حدّث وثائقك للمتابعة.' },
  ]},
  { id: 'c-complaint', name: 'الشكاوى', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'complaint_title', label: 'العنوان', ar: 'تقديم شكوى' },
    { key: 'complaint_pick_order', label: 'اختيار الطلب', ar: 'اختر الطلب المرتبط' },
    { key: 'complaint_general', label: 'عامة', ar: 'شكوى عامة (غير مرتبطة بطلب)' },
    { key: 'complaint_desc', label: 'الوصف', ar: 'اشرح المشكلة بالتفصيل' },
    { key: 'btn_send_complaint', label: 'إرسال', ar: 'إرسال الشكوى' },
    { key: 'complaint_ok_title', label: 'نجاح', ar: 'تم إرسال الشكوى بنجاح' },
    { key: 'complaint_ok_desc', label: 'النص', ar: 'رقم الشكوى: #{id}. سيتم مراجعتها من قبل الإدارة خلال 24 ساعة.' },
    { key: 'my_complaints', label: 'شكاواي', ar: 'شكاواي' },
  ]},
  { id: 'c-notifs', name: 'الإشعارات داخل التطبيق', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'notifs_title', label: 'العنوان', ar: 'الإشعارات' },
    { key: 'notifs_mark_all', label: 'مقروء', ar: 'تحديد الكل كمقروء' },
    { key: 'notifs_empty', label: 'فارغ', ar: 'لا توجد إشعارات 📭' },
  ]},
  { id: 'c-password', name: 'تغيير كلمة المرور', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'pw_title', label: 'العنوان', ar: 'تغيير كلمة المرور' },
    { key: 'pw_current', label: 'الحالية', ar: 'كلمة المرور الحالية' },
    { key: 'pw_new', label: 'الجديدة', ar: 'كلمة المرور الجديدة' },
    { key: 'pw_confirm', label: 'التأكيد', ar: 'تأكيد كلمة المرور الجديدة' },
    { key: 'err_pw_current', label: 'خاطئة', ar: 'كلمة المرور الحالية غير صحيحة.' },
    { key: 'err_pw_short', label: 'قصيرة', ar: 'كلمة المرور قصيرة جداً.' },
    { key: 'err_pw_same', label: 'نفس القديمة', ar: 'كلمة المرور الجديدة يجب أن تكون مختلفة عن الحالية.' },
  ]},
  { id: 'c-support', name: 'الدعم ومعلومات التطبيق', app: 'الكابتن', group: 'الدعم', fields: [
    { key: 'about_title', label: 'معلومات', ar: 'معلومات التطبيق' },
    { key: 'support_title', label: 'الدعم', ar: 'تواصل مع الدعم' },
    { key: 'lang_title', label: 'اللغة', ar: 'تغيير اللغة' },
    { key: 'delete_account', label: 'حذف الحساب', ar: 'حذف الحساب' },
    { key: 'delete_account_hint', label: 'شرط الحذف', ar: 'لا يمكن الحذف مع طلبات نشطة أو مبالغ غير مسوّاة.' },
  ]},
]

export const STORE_SCREENS: CatalogScreen[] = [
  { id: 's-welcome', name: 'شاشة الترحيب', app: 'المحل', group: 'الدخول والتسجيل', fields: [
    { key: 'store_welcome_title', label: 'العنوان', ar: 'أهلاً بك في تطبيق محل زاجل ديلفري!' },
    { key: 'store_welcome_subtitle', label: 'النص', ar: 'يوصلك بسرعة وثقة - اطلب كباتن توصيل لطلبياتك بكل سهولة وبدون تعقيد.' },
    { key: 'btn_store_register', label: 'تسجيل', ar: 'تسجيل محل / مطعم جديد' },
    { key: 'btn_store_login', label: 'دخول', ar: 'لديّ حساب بالفعل' },
  ]},
  { id: 's-signup-1', name: 'التسجيل — بيانات المحل', app: 'المحل', group: 'الدخول والتسجيل', fields: [
    { key: 'store_signup_title', label: 'العنوان', ar: 'تسجيل محل جديد' },
    { key: 'field_store_name', label: 'اسم المحل', ar: 'اسم المحل أو المطعم' },
    { key: 'field_business_type', label: 'نوع النشاط', ar: 'نوع النشاط التجاري' },
    { key: 'field_owner_name', label: 'المالك', ar: 'اسم صاحب المحل' },
    { key: 'field_store_phone', label: 'الهاتف', ar: 'رقم الهاتف' },
  ]},
  { id: 's-signup-2', name: 'التسجيل — الموقع', app: 'المحل', group: 'الدخول والتسجيل', fields: [
    { key: 'field_store_location', label: 'الموقع', ar: 'تحديد موقع المحل على الخريطة 📍' },
    { key: 'location_hint', label: 'التوضيح', ar: 'سيتم استخدام الموقع لتحديد منطقة التوصيل وحساب الأجرة' },
    { key: 'btn_use_gps', label: 'موقعي', ar: 'استخدام موقعي الحالي' },
    { key: 'err_gps_denied', label: 'رفض GPS', ar: 'لم نتمكن من تحديد موقعك. يرجى تحريك الخريطة يدوياً' },
    { key: 'field_address', label: 'العنوان', ar: 'العنوان التفصيلي' },
    { key: 'inside_zone', label: 'داخل النطاق', ar: 'محلك يقع في منطقة: {zone} ✅' },
    { key: 'outside_zone', label: 'خارج النطاق', ar: '⚠️ موقعك خارج المناطق المحددة. تواصل مع الإدارة.' },
  ]},
  { id: 's-signup-3', name: 'التسجيل — المراجعة', app: 'المحل', group: 'الدخول والتسجيل', fields: [
    { key: 'store_review_title', label: 'العنوان', ar: 'مراجعة البيانات' },
    { key: 'btn_send_store', label: 'إرسال', ar: 'إرسال الطلب ✅' },
    { key: 'store_pending_text', label: 'انتظار', ar: 'محلك قيد المراجعة' },
  ]},
  { id: 's-login', name: 'تسجيل الدخول / الاستعادة', app: 'المحل', group: 'الدخول والتسجيل', fields: [
    { key: 'store_login_title', label: 'دخول', ar: 'تسجيل الدخول' },
    { key: 'store_forgot_title', label: 'استعادة', ar: 'استعادة كلمة المرور' },
  ]},
  { id: 's-rejected', name: 'الرفض وإعادة التقديم', app: 'المحل', group: 'حالات الحساب', fields: [
    { key: 'store_reject_title', label: 'العنوان', ar: 'تم رفض طلب التسجيل' },
    { key: 'store_reapply_banner', label: 'تنبيه', ar: 'تم رفض طلبك السابق. يمكنك تعديل البيانات وإعادة التقديم.' },
  ]},
  { id: 's-suspended', name: 'محل موقوف', app: 'المحل', group: 'حالات الحساب', fields: [
    { key: 'store_suspended_title', label: 'العنوان', ar: 'محلك موقوف حالياً' },
    { key: 'store_suspended_body', label: 'النص', ar: 'تم إيقاف حساب محلك مؤقتاً. سبب الإيقاف: {reason}. يمكنك الاطلاع على طلباتك السابقة أو التواصل مع قسم الدعم.' },
    { key: 'store_suspended_no_create', label: 'منع الإنشاء', ar: 'لا يمكنك إنشاء طلبات جديدة حتى يتم إعادة التفعيل.' },
    { key: 'btn_view_past', label: 'السجل', ar: '📋 عرض سجل الطلبات السابقة' },
  ]},
  { id: 's-session', name: 'انتهاء الجلسة / صيانة / تحديث', app: 'المحل', group: 'حالات الحساب', fields: [
    { key: 'store_session_title', label: 'جلسة', ar: 'انتهت جلستك' },
    { key: 'store_maintenance', label: 'صيانة', ar: 'نعتذر عن الإزعاج. النظام في وضع صيانة مؤقت.' },
    { key: 'store_update_required', label: 'تحديث', ar: 'تحديث مطلوب' },
  ]},
  { id: 's-home', name: 'الشاشة الرئيسية', app: 'المحل', group: 'التشغيل', fields: [
    { key: 'btn_create_order', label: 'إنشاء طلب', ar: '+ إنشاء طلب جديد 🚚' },
    { key: 'home_active', label: 'النشطة', ar: 'طلباتك النشطة' },
    { key: 'home_no_active', label: 'فارغ', ar: 'لا توجد طلبات نشطة 📭' },
    { key: 'stat_today', label: 'اليوم', ar: 'طلبات اليوم' },
    { key: 'stat_done', label: 'مكتملة', ar: 'طلبات مكتملة' },
    { key: 'stat_canceled', label: 'ملغاة', ar: 'طلبات ملغاة' },
    { key: 'nav_home', label: 'رئيسية', ar: 'الرئيسية' },
    { key: 'nav_history', label: 'سجل', ar: 'سجل الطلبات' },
    { key: 'nav_reports', label: 'تقارير', ar: 'التقارير' },
    { key: 'nav_profile', label: 'ملف', ar: 'الملف الشخصي' },
  ]},
  { id: 's-create-1', name: 'إنشاء طلب — بيانات الزبون', app: 'المحل', group: 'إنشاء الطلب', fields: [
    { key: 'title_create_order', label: 'العنوان', ar: 'إنشاء طلبية توصيل جديدة' },
    { key: 'step_customer_info', label: 'خطوة 1', ar: '1. بيانات الزبون' },
    { key: 'field_customer_name', label: 'الاسم', ar: 'اسم الزبون' },
    { key: 'field_customer_phone', label: 'الهاتف', ar: 'رقم هاتف الزبون' },
    { key: 'field_access_notes', label: 'ملاحظات الوصول', ar: 'ملاحظات الوصول والزيارة' },
    { key: 'err_customer_name', label: 'خطأ الاسم', ar: 'اسم الزبون مطلوب' },
    { key: 'err_customer_phone', label: 'خطأ الهاتف', ar: 'رقم هاتف صحيح مطلوب' },
  ]},
  { id: 's-create-2', name: 'إنشاء طلب — موقع التوصيل', app: 'المحل', group: 'إنشاء الطلب', fields: [
    { key: 'step_dropoff_location', label: 'خطوة 2', ar: '2. موقع التوصيل' },
    { key: 'field_dropoff_address', label: 'العنوان', ar: 'العنوان التفصيلي للتوصيل' },
    { key: 'calc_delivery_fee', label: 'الأجرة', ar: 'أجرة التوصيل المحسوبة:' },
    { key: 'err_no_fee', label: 'بدون أجرة', ar: '⚠️ لم يتم تحديد أجرة التوصيل. تأكد من صحة المنطقة.' },
    { key: 'err_need_pin', label: 'بدون موقع', ar: 'يرجى تحديد موقع التوصيل' },
    { key: 'pin_confirm', label: 'تأكيد الموقع', ar: '📍 الموقع المحدد' },
    { key: 'link_edit_pin', label: 'تعديل', ar: 'تعديل الموقع' },
    { key: 'link_ok_pin', label: 'تأكيد', ar: 'تأكيد الموقع ✅' },
  ]},
  { id: 's-create-3', name: 'إنشاء طلب — المراجعة والإرسال', app: 'المحل', group: 'إنشاء الطلب', fields: [
    { key: 'step_order_summary', label: 'خطوة 3', ar: '3. تفاصيل المبلغ والمراجعة' },
    { key: 'field_order_value', label: 'قيمة الطلب', ar: 'قيمة الطلبية (المبلغ المطلوب من المحل)' },
    { key: 'field_order_value_hint', label: 'تلميح', ar: 'هذا المبلغ سيدفعه الكابتن لك نقداً (كاش) فور استلام الطلبية.' },
    { key: 'calc_total_customer_pays', label: 'إجمالي الزبون', ar: 'إجمالي المبلغ المطلوب تحصيله من الزبون (قيمة الطلبية + التوصيل):' },
    { key: 'btn_submit_dispatch', label: 'إرسال', ar: '🚚 إرسال الطلبية وطلب كابتن زاجل' },
    { key: 'toggle_prefer_captain', label: 'كابتن محدد', ar: '🔘 طلب كابتن محدد (اختياري)' },
    { key: 'select_preferred_captain', label: 'اختيار', ar: 'اختر كابتن من القائمة المفضلة لديك:' },
    { key: 'creating', label: 'تحميل', ar: 'جاري إنشاء الطلب والبحث عن كابتن...' },
    { key: 'err_maintenance_create', label: 'صيانة', ar: '⚠️ النظام في وضع صيانة حالياً. لا يمكن إنشاء طلبات جديدة.' },
    { key: 'captain_offline_q', label: 'غير متصل', ar: 'الكابتن غير متصل حالياً. هل تريد إرسال الطلب للطابور العام؟' },
  ]},
  { id: 's-sent', name: 'تأكيد الإرسال', app: 'المحل', group: 'إنشاء الطلب', fields: [
    { key: 'sent_title', label: 'العنوان', ar: 'تم إرسال الطلب بنجاح!' },
    { key: 'sent_desc', label: 'النص', ar: 'جاري البحث عن كابتن قريب... سيتم إشعارك عند قبول كابتن لطلبك.' },
    { key: 'btn_track', label: 'متابعة', ar: '📋 متابعة الطلب' },
    { key: 'btn_home', label: 'رئيسية', ar: '🏠 العودة للرئيسية' },
  ]},
  { id: 's-track', name: 'متابعة الطلب', app: 'المحل', group: 'المتابعة', fields: [
    { key: 'track_title', label: 'العنوان', ar: 'متابعة الطلب' },
    { key: 'status_searching_captain', label: 'بحث', ar: '🟡 جاري البحث عن كابتن زاجل قريب...' },
    { key: 'status_captain_accepted', label: 'قبول', ar: '🔵 الكابتن {captain_name} قبل الطلبية وهو في طريقه إليك' },
    { key: 'status_captain_arrived', label: 'وصل', ar: '🔵 الكابتن وصل لموقع محلك لاستلام الطلبية' },
    { key: 'status_captain_picked', label: 'استلام', ar: '🔵 الكابتن استلم الطلبية ودفعلكم الكاش وهو بالطريق للزبون' },
    { key: 'status_delivered_success', label: 'تسليم', ar: '🟢 تم تسليم الطلبية للزبون بنجاح ✅' },
    { key: 'status_cancelled', label: 'إلغاء', ar: '🔴 الطلبية ملغاة - السبب: {cancel_reason}' },
    { key: 'btn_cancel_order', label: 'إلغاء', ar: '❌ إلغاء الطلب' },
    { key: 'btn_call_captain', label: 'اتصال كابتن', ar: '📞 تواصل مع الكابتن' },
    { key: 'btn_call_support', label: 'دعم', ar: '📞 تواصل مع الدعم' },
    { key: 'cancel_after_pickup', label: 'بعد الاستلام', ar: 'لا يمكن إلغاء الطلب بعد استلام الكابتن له. تواصل مع الإدارة.' },
  ]},
  { id: 's-no-captain', name: 'لا يوجد كباتن', app: 'المحل', group: 'المتابعة', fields: [
    { key: 'no_captain_title', label: 'العنوان', ar: 'لم يتم العثور على كابتن' },
    { key: 'no_captain_desc', label: 'النص', ar: 'لم يقبل أي كابتن طلبك خلال المدة المحددة. جاري المحاولة مرة أخرى...' },
    { key: 'btn_keep_waiting', label: 'انتظار', ar: '⏳ الاستمرار في الانتظار' },
    { key: 'auto_cancel_notice', label: 'إلغاء تلقائي', ar: 'تم إلغاء الطلب تلقائياً لعدم توفر كباتن متاحين حالياً. يرجى المحاولة لاحقاً' },
  ]},
  { id: 's-edit-order', name: 'تعديل الطلب', app: 'المحل', group: 'المتابعة', fields: [
    { key: 'edit_order_title', label: 'العنوان', ar: 'تعديل الطلب' },
  ]},
  { id: 's-rate', name: 'تقييم الكابتن', app: 'المحل', group: 'المتابعة', fields: [
    { key: 'btn_rate_captain', label: 'الزر', ar: '⭐ تقييم كابتن زاجل' },
    { key: 'rate_modal_title', label: 'العنوان', ar: 'كيف كانت تجربتك مع الكابتن {captain_name}؟' },
    { key: 'rate_question_prepared', label: 'الجاهزية', ar: 'هل كانت الطلبية جاهزة فور وصول الكابتن؟' },
    { key: 'err_need_stars', label: 'بدون نجوم', ar: 'يرجى اختيار تقييم' },
  ]},
  { id: 's-history', name: 'سجل الطلبات والتفاصيل', app: 'المحل', group: 'التقارير', fields: [
    { key: 'store_history_title', label: 'السجل', ar: 'سجل الطلبات' },
    { key: 'store_history_search', label: 'بحث', ar: 'ابحث برقم الطلب أو اسم الزبون أو رقم الهاتف' },
    { key: 'completed_title', label: 'مكتمل', ar: 'تفاصيل الطلب' },
  ]},
  { id: 's-reports', name: 'تقارير المحل', app: 'المحل', group: 'التقارير', fields: [
    { key: 'store_reports_title', label: 'العنوان', ar: 'تقارير محلك' },
  ]},
  { id: 's-profile', name: 'الملف الشخصي وتعديل البيانات', app: 'المحل', group: 'الحساب', fields: [
    { key: 'store_profile_title', label: 'الملف', ar: 'الملف الشخصي' },
    { key: 'edit_store_title', label: 'تعديل', ar: 'تعديل بيانات المحل' },
    { key: 'edit_location_q', label: 'تغيير الموقع', ar: 'هل تريد تغيير موقع محلك؟ قد يتغير تصنيف المنطقة وأجرة التوصيل.' },
    { key: 'edit_saved', label: 'فوري', ar: 'تم تحديث البيانات بنجاح.' },
    { key: 'edit_pending', label: 'مراجعة', ar: 'تم إرسال التعديلات للمراجعة.' },
  ]},
  { id: 's-complaint', name: 'الشكاوى والإشعارات والدعم', app: 'المحل', group: 'الحساب', fields: [
    { key: 'store_complaint_title', label: 'شكوى', ar: 'تقديم شكوى' },
    { key: 'store_notifs', label: 'إشعارات', ar: 'الإشعارات' },
    { key: 'store_support', label: 'دعم', ar: 'تواصل مع الدعم' },
    { key: 'store_delete', label: 'حذف', ar: 'حذف الحساب' },
  ]},
  { id: 's-return', name: 'استلام المرتجع', app: 'المحل', group: 'المتابعة', fields: [
    { key: 'return_title', label: 'العنوان', ar: 'تأكيد استلام المرتجع' },
    { key: 'return_hint', label: 'النص', ar: 'افحص الأغراض وأعد الكاش للكابتن ثم أكّد.' },
  ]},
]

export const CAPTAIN_COPY: CatalogCopy[] = CAPTAIN_SCREENS.flatMap((s) =>
  s.fields.map((f) => ({ key: f.key, ar: f.ar, place: `الكابتن — ${s.name}` })),
)

export const STORE_COPY: CatalogCopy[] = STORE_SCREENS.flatMap((s) =>
  s.fields.map((f) => ({ key: f.key, ar: f.ar, place: `المحل — ${s.name}` })),
)

export const CATALOG_TEMPLATES: CatalogTpl[] = [
  { event: 'طلب جديد للكابتن', to: 'الكابتن', channel: 'Push', title: '🚚 طلبية جديدة قريبة منك!', body: 'طلب جديد من {shop_name} في منطقة {pickup_district}. اضغط لفتح التطبيق والقبول.' },
  { event: 'موافقة حساب كابتن', to: 'الكابتن', channel: 'Push', title: 'مرحبًا بك!', body: 'تمت الموافقة على حسابك! مرحبًا بك.' },
  { event: 'رفض حساب كابتن', to: 'الكابتن', channel: 'Push', title: 'تم رفض الطلب', body: 'تم رفض طلب التسجيل. السبب: {rejection_reason}' },
  { event: 'إيقاف كابتن', to: 'الكابتن', channel: 'Push', title: 'حساب الكابتن موقوف حالياً 🚫', body: 'تم إيقاف حسابك. السبب: {reason}' },
  { event: 'إعادة تفعيل كابتن', to: 'الكابتن', channel: 'Push', title: 'تم إعادة تفعيل حسابك', body: 'تم إعادة تفعيل حسابك. مرحبًا بعودتك!' },
  { event: 'تحديث وثائق', to: 'الكابتن', channel: 'Push', title: 'وثائقك تحتاج تحديث', body: 'يرجى تحديث وثائقك خلال 48 ساعة.' },
  { event: 'تعيين كابتن للمحل', to: 'المحل', channel: 'Push', title: 'تم تعيين كابتن لطلبك #{order_id}', body: 'الكابتن {captain_name} قبل طلبك وهو في طريقه لمكان المحل.' },
  { event: 'الكابتن في الطريق', to: 'المحل', channel: 'Push', title: 'الكابتن في طريقه لموقعك', body: 'الكابتن {captain_name} متوجه لمحلك.' },
  { event: 'وصول الكابتن', to: 'المحل', channel: 'Push', title: 'الكابتن وصل', body: 'الكابتن {captain_name} وصل لموقعك' },
  { event: 'استلام الطلب', to: 'المحل', channel: 'Push', title: 'تم الاستلام', body: 'الكابتن استلم الطلب وهو بالطريق للزبون' },
  { event: 'تسليم الطلب', to: 'المحل', channel: 'Push', title: 'تم التسليم بنجاح! ✅', body: 'الطلبية #{order_id} تم تسليمها للزبون {customer_name} بنجاح.' },
  { event: 'إلغاء الطلب', to: 'الكل', channel: 'Push', title: 'طلب ملغي', body: 'تم إلغاء الطلب #{order_id}. السبب: {cancel_reason}' },
  { event: 'إيقاف محل', to: 'المحل', channel: 'Push', title: 'حساب المحل موقوف حالياً 🚫', body: 'تم إيقاف حساب محلك. السبب: {reason}' },
  { event: 'طلب عالق', to: 'الإدارة', channel: 'Dashboard', title: '⚠️ تنبيه: طلبية عالقة بدون كابتن!', body: 'الطلبية #{order_id} من محل {shop_name} تنتظر كابتن منذ أكثر من {waiting_time} دقيقة.' },
]

export const CATALOG_AUTO = [
  { state: 'وضع الصيانة', message: 'نعتذر عن الإزعاج. النظام في وضع صيانة مؤقت. سنعود قريباً.', app: 'الكل' },
  { state: 'خارج الشفت', message: 'أنت خارج وقت شفتك. لا يمكنك الاتصال الآن.', app: 'الكابتن' },
  { state: 'الحد الأقصى', message: 'لقد وصلت للحد الأقصى من الطلبات النشطة.', app: 'الكابتن' },
  { state: 'محل موقوف', message: 'محلك موقوف حالياً. تواصل مع الإدارة.', app: 'المحل' },
  { state: 'كابتن موقوف', message: 'تم إيقاف حسابك من قبل الإدارة.', app: 'الكابتن' },
  { state: 'انتهاء الجلسة', message: 'انتهت جلستك. سجّل الدخول مجدداً.', app: 'الكل' },
  { state: 'لا يوجد كباتن', message: 'لا يوجد كباتن متاحون حالياً. سنحاول لاحقاً.', app: 'المحل' },
  { state: 'وضع عدم الاتصال', message: '⚠️ وضع عدم الاتصال. يمكنك إكمال التوصيل الحالي فقط.', app: 'الكابتن' },
  { state: 'تحديث إجباري', message: 'إصدار تطبيقك الحالي قديم ولا يدعم الاستمرار. يرجى التحديث للمتابعة.', app: 'الكل' },
]

export const CATALOG_SMS = [
  { key: 'sms_otp_template', ar: 'رمز التحقق لتسلم طلبيتك من {shop_name} عبر زاجل ديلفري هو: {otp_code}. يرجى إعطاؤه للكابتن عند التسليم. يوصلك بسرعة وثقة!', place: 'SMS الزبون' },
]

export const CATALOG_OPTIONS: CatalogOption[] = [
  { id: 'v1', group: 'أنواع المركبات', app: 'الكابتن', label: 'دراجة نارية 🏍️' },
  { id: 'v2', group: 'أنواع المركبات', app: 'الكابتن', label: 'سيارة 🚗' },
  { id: 'v3', group: 'أنواع المركبات', app: 'الكابتن', label: 'دراجة هوائية 🚲' },
  { id: 'v4', group: 'أنواع المركبات', app: 'الكابتن', label: 'مشي على الأقدام 🚶' },
  { id: 'b1', group: 'أنواع النشاط', app: 'المحل', label: 'مطعم 🍕' },
  { id: 'b2', group: 'أنواع النشاط', app: 'المحل', label: 'سوبرماركت / مأكولات 🛒' },
  { id: 'b3', group: 'أنواع النشاط', app: 'المحل', label: 'صيدلية 💊' },
  { id: 'b4', group: 'أنواع النشاط', app: 'المحل', label: 'محل تجاري / متجر 🛍️' },
  { id: 'b5', group: 'أنواع النشاط', app: 'المحل', label: 'أخرى' },
  { id: 'cc1', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'تعطل الدراجة' },
  { id: 'cc2', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'حادث' },
  { id: 'cc3', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'الزبون لا يرد' },
  { id: 'cc4', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'العنوان خاطئ' },
  { id: 'cc5', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'المحل ألغى' },
  { id: 'cc6', group: 'أسباب إلغاء الكابتن', app: 'الكابتن', label: 'أخرى' },
  { id: 'sc1', group: 'أسباب إلغاء المحل', app: 'المحل', label: 'الزبون ألغى' },
  { id: 'sc2', group: 'أسباب إلغاء المحل', app: 'المحل', label: 'خطأ في البيانات' },
  { id: 'sc3', group: 'أسباب إلغاء المحل', app: 'المحل', label: 'تأخر الكابتن' },
  { id: 'sc4', group: 'أسباب إلغاء المحل', app: 'المحل', label: 'أخرى' },
  { id: 'i1', group: 'مشاكل التسليم', app: 'الكابتن', label: '📞 الزبون لا يرد على الهاتف' },
  { id: 'i2', group: 'مشاكل التسليم', app: 'الكابتن', label: '🏠 الزبون غير موجود في العنوان' },
  { id: 'i3', group: 'مشاكل التسليم', app: 'الكابتن', label: '❌ الزبون يرفض استلام الطلب' },
  { id: 'i4', group: 'مشاكل التسليم', app: 'الكابتن', label: '💰 الزبون يرفض الدفع' },
  { id: 'i5', group: 'مشاكل التسليم', app: 'الكابتن', label: '📍 العنوان خاطئ أو غير دقيق' },
  { id: 'i6', group: 'مشاكل التسليم', app: 'الكابتن', label: '🚪 لا أستطيع الوصول للموقع' },
  { id: 'i7', group: 'مشاكل التسليم', app: 'الكابتن', label: '❓ مشكلة أخرى' },
  { id: 'k1', group: 'أنواع الشكاوى', app: 'الكل', label: '🚚 مشكلة في التوصيل' },
  { id: 'k2', group: 'أنواع الشكاوى', app: 'الكل', label: '💰 مشكلة في المبلغ' },
  { id: 'k3', group: 'أنواع الشكاوى', app: 'الكل', label: '📦 مشكلة في التسليم' },
  { id: 'k4', group: 'أنواع الشكاوى', app: 'الكل', label: '🤝 مشكلة مع الطرف الآخر' },
  { id: 'k5', group: 'أنواع الشكاوى', app: 'الكل', label: '📱 مشكلة تقنية' },
  { id: 'k6', group: 'أنواع الشكاوى', app: 'الكل', label: '❓ أخرى' },
  { id: 'l1', group: 'اللغات', app: 'الكل', label: 'العربية' },
  { id: 'l2', group: 'اللغات', app: 'الكل', label: 'الكردية' },
  { id: 'l3', group: 'اللغات', app: 'الكل', label: 'الإنجليزية' },
]

export const CATALOG_FAQ = [
  { q: 'كيف أسجّل ككابتن؟', a: 'حمّل تطبيق الكابتن واضغط على تسجيل حساب جديد ثم ارفع الوثائق الأربع.', app: 'الكابتن' },
  { q: 'كيف أنشئ طلباً؟', a: 'من الشاشة الرئيسية اضغط على إنشاء طلب جديد وأدخل بيانات الزبون وموقع التوصيل.', app: 'المحل' },
  { q: 'ماذا لو الزبون لا يرد؟', a: 'سجّل مشكلة التسليم وانتظر 10 دقائق ثم أرجع الطلبية للمحل واسترد الكاش.', app: 'الكابتن' },
  { q: 'هل يمكن تعديل الطلب بعد الإنشاء؟', a: 'نعم حسب المرحلة: كامل أثناء البحث، محدود بعد القبول، وممنوع بعد الاستلام.', app: 'المحل' },
]

export const CATALOG_LEGAL = [
  { title: 'شروط الاستخدام — الكابتن', body: '' },
  { title: 'شروط الاستخدام — المحل', body: '' },
  { title: 'سياسة الخصوصية', body: '' },
  { title: 'سياسة الإلغاء والاسترجاع', body: '' },
]

export const ALL_SCREENS = [...CAPTAIN_SCREENS, ...STORE_SCREENS]
export const ALL_COPY = [...CAPTAIN_COPY, ...STORE_COPY]
